// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OauthProviders int32

const (
	OauthProviders_YANDEX OauthProviders = 0
)

// Enum value maps for OauthProviders.
var (
	OauthProviders_name = map[int32]string{
		0: "YANDEX",
	}
	OauthProviders_value = map[string]int32{
		"YANDEX": 0,
	}
)

func (x OauthProviders) Enum() *OauthProviders {
	p := new(OauthProviders)
	*p = x
	return p
}

func (x OauthProviders) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OauthProviders) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_auth_proto_enumTypes[0].Descriptor()
}

func (OauthProviders) Type() protoreflect.EnumType {
	return &file_proto_auth_auth_proto_enumTypes[0]
}

func (x OauthProviders) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OauthProviders.Descriptor instead.
func (OauthProviders) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	About         *string                `protobuf:"bytes,4,opt,name=about,proto3,oneof" json:"about,omitempty"`
	Skills        []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,6,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetAbout() string {
	if x != nil && x.About != nil {
		return *x.About
	}
	return ""
}

func (x *RegisterRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *RegisterRequest) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TotpPin       *string                `protobuf:"bytes,3,opt,name=totp_pin,json=totpPin,proto3,oneof" json:"totp_pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetTotpPin() string {
	if x != nil && x.TotpPin != nil {
		return *x.TotpPin
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SessionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionType) Reset() {
	*x = SessionType{}
	mi := &file_proto_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionType) ProtoMessage() {}

func (x *SessionType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionType.ProtoReflect.Descriptor instead.
func (*SessionType) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SessionType) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionType) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionType) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type GetCurrentSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSessionRequest) Reset() {
	*x = GetCurrentSessionRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSessionRequest) ProtoMessage() {}

func (x *GetCurrentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSessionRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetCurrentSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetCurrentSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionType           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSessionResponse) Reset() {
	*x = GetCurrentSessionResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSessionResponse) ProtoMessage() {}

func (x *GetCurrentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSessionResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetCurrentSessionResponse) GetSession() *SessionType {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetAllUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserSessionsRequest) Reset() {
	*x = GetAllUserSessionsRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserSessionsRequest) ProtoMessage() {}

func (x *GetAllUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionType         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserSessionsResponse) Reset() {
	*x = GetAllUserSessionsResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserSessionsResponse) ProtoMessage() {}

func (x *GetAllUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllUserSessionsResponse) GetSessions() []*SessionType {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type OauthLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OauthProviders         `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.OauthProviders" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthLoginRequest) Reset() {
	*x = OauthLoginRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthLoginRequest) ProtoMessage() {}

func (x *OauthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthLoginRequest.ProtoReflect.Descriptor instead.
func (*OauthLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *OauthLoginRequest) GetProvider() OauthProviders {
	if x != nil {
		return x.Provider
	}
	return OauthProviders_YANDEX
}

type OauthLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthLoginResponse) Reset() {
	*x = OauthLoginResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthLoginResponse) ProtoMessage() {}

func (x *OauthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthLoginResponse.ProtoReflect.Descriptor instead.
func (*OauthLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *OauthLoginResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type OauthCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OauthProviders         `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.OauthProviders" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthCallbackRequest) Reset() {
	*x = OauthCallbackRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthCallbackRequest) ProtoMessage() {}

func (x *OauthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthCallbackRequest.ProtoReflect.Descriptor instead.
func (*OauthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *OauthCallbackRequest) GetProvider() OauthProviders {
	if x != nil {
		return x.Provider
	}
	return OauthProviders_YANDEX
}

func (x *OauthCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type OauthCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthCallbackResponse) Reset() {
	*x = OauthCallbackResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthCallbackResponse) ProtoMessage() {}

func (x *OauthCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthCallbackResponse.ProtoReflect.Descriptor instead.
func (*OauthCallbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{15}
}

func (x *OauthCallbackResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EnableTotpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableTotpRequest) Reset() {
	*x = EnableTotpRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableTotpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTotpRequest) ProtoMessage() {}

func (x *EnableTotpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTotpRequest.ProtoReflect.Descriptor instead.
func (*EnableTotpRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{16}
}

func (x *EnableTotpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EnableTotpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	QrcodeUrl     string                 `protobuf:"bytes,2,opt,name=qrcode_url,json=qrcodeUrl,proto3" json:"qrcode_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableTotpResponse) Reset() {
	*x = EnableTotpResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableTotpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTotpResponse) ProtoMessage() {}

func (x *EnableTotpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTotpResponse.ProtoReflect.Descriptor instead.
func (*EnableTotpResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{17}
}

func (x *EnableTotpResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *EnableTotpResponse) GetQrcodeUrl() string {
	if x != nil {
		return x.QrcodeUrl
	}
	return ""
}

var File_proto_auth_auth_proto protoreflect.FileDescriptor

const file_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x15proto/auth/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"\xbc\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x19\n" +
	"\x05about\x18\x04 \x01(\tH\x00R\x05about\x88\x01\x01\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\x12\x1b\n" +
	"\x06avatar\x18\x06 \x01(\fH\x01R\x06avatar\x88\x01\x01B\b\n" +
	"\x06_aboutB\t\n" +
	"\a_avatar\"\"\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1e\n" +
	"\btotp_pin\x18\x03 \x01(\tH\x00R\atotpPin\x88\x01\x01B\v\n" +
	"\t_totp_pin\".\n" +
	"\rLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\" \n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"d\n" +
	"\vSessionType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\"9\n" +
	"\x18GetCurrentSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"H\n" +
	"\x19GetCurrentSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.auth.SessionTypeR\asession\"4\n" +
	"\x19GetAllUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x1aGetAllUserSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.auth.SessionTypeR\bsessions\"E\n" +
	"\x11OauthLoginRequest\x120\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x14.auth.OauthProvidersR\bprovider\"&\n" +
	"\x12OauthLoginResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\\\n" +
	"\x14OauthCallbackRequest\x120\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x14.auth.OauthProvidersR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"6\n" +
	"\x15OauthCallbackResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\")\n" +
	"\x11EnableTotpRequest\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"K\n" +
	"\x12EnableTotpResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"qrcode_url\x18\x02 \x01(\tR\tqrcodeUrl*\x1c\n" +
	"\x0eOauthProviders\x12\n" +
	"\n" +
	"\x06YANDEX\x10\x002\xe4\x04\n" +
	"\x04Auth\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x123\n" +
	"\x06Verify\x12\x13.auth.VerifyRequest\x1a\x14.auth.VerifyResponse\x12?\n" +
	"\vVerifyEmail\x12\x18.auth.VerifyEmailRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x11GetCurrentSession\x12\x1e.auth.GetCurrentSessionRequest\x1a\x1f.auth.GetCurrentSessionResponse\x12W\n" +
	"\x12GetAllUserSessions\x12\x1f.auth.GetAllUserSessionsRequest\x1a .auth.GetAllUserSessionsResponse\x12?\n" +
	"\n" +
	"OauthLogin\x12\x17.auth.OauthLoginRequest\x1a\x18.auth.OauthLoginResponse\x12H\n" +
	"\rOauthCallback\x12\x1a.auth.OauthCallbackRequest\x1a\x1b.auth.OauthCallbackResponse\x12?\n" +
	"\n" +
	"EnableTotp\x12\x17.auth.EnableTotpRequest\x1a\x18.auth.EnableTotpResponseB\aZ\x05/authb\x06proto3"

var (
	file_proto_auth_auth_proto_rawDescOnce sync.Once
	file_proto_auth_auth_proto_rawDescData []byte
)

func file_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)))
	})
	return file_proto_auth_auth_proto_rawDescData
}

var file_proto_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_auth_auth_proto_goTypes = []any{
	(OauthProviders)(0),                // 0: auth.OauthProviders
	(*RegisterRequest)(nil),            // 1: auth.RegisterRequest
	(*RegisterResponse)(nil),           // 2: auth.RegisterResponse
	(*LoginRequest)(nil),               // 3: auth.LoginRequest
	(*LoginResponse)(nil),              // 4: auth.LoginResponse
	(*VerifyRequest)(nil),              // 5: auth.VerifyRequest
	(*VerifyResponse)(nil),             // 6: auth.VerifyResponse
	(*VerifyEmailRequest)(nil),         // 7: auth.VerifyEmailRequest
	(*SessionType)(nil),                // 8: auth.SessionType
	(*GetCurrentSessionRequest)(nil),   // 9: auth.GetCurrentSessionRequest
	(*GetCurrentSessionResponse)(nil),  // 10: auth.GetCurrentSessionResponse
	(*GetAllUserSessionsRequest)(nil),  // 11: auth.GetAllUserSessionsRequest
	(*GetAllUserSessionsResponse)(nil), // 12: auth.GetAllUserSessionsResponse
	(*OauthLoginRequest)(nil),          // 13: auth.OauthLoginRequest
	(*OauthLoginResponse)(nil),         // 14: auth.OauthLoginResponse
	(*OauthCallbackRequest)(nil),       // 15: auth.OauthCallbackRequest
	(*OauthCallbackResponse)(nil),      // 16: auth.OauthCallbackResponse
	(*EnableTotpRequest)(nil),          // 17: auth.EnableTotpRequest
	(*EnableTotpResponse)(nil),         // 18: auth.EnableTotpResponse
	(*emptypb.Empty)(nil),              // 19: google.protobuf.Empty
}
var file_proto_auth_auth_proto_depIdxs = []int32{
	8,  // 0: auth.GetCurrentSessionResponse.session:type_name -> auth.SessionType
	8,  // 1: auth.GetAllUserSessionsResponse.sessions:type_name -> auth.SessionType
	0,  // 2: auth.OauthLoginRequest.provider:type_name -> auth.OauthProviders
	0,  // 3: auth.OauthCallbackRequest.provider:type_name -> auth.OauthProviders
	1,  // 4: auth.Auth.Register:input_type -> auth.RegisterRequest
	3,  // 5: auth.Auth.Login:input_type -> auth.LoginRequest
	5,  // 6: auth.Auth.Verify:input_type -> auth.VerifyRequest
	7,  // 7: auth.Auth.VerifyEmail:input_type -> auth.VerifyEmailRequest
	9,  // 8: auth.Auth.GetCurrentSession:input_type -> auth.GetCurrentSessionRequest
	11, // 9: auth.Auth.GetAllUserSessions:input_type -> auth.GetAllUserSessionsRequest
	13, // 10: auth.Auth.OauthLogin:input_type -> auth.OauthLoginRequest
	15, // 11: auth.Auth.OauthCallback:input_type -> auth.OauthCallbackRequest
	17, // 12: auth.Auth.EnableTotp:input_type -> auth.EnableTotpRequest
	2,  // 13: auth.Auth.Register:output_type -> auth.RegisterResponse
	4,  // 14: auth.Auth.Login:output_type -> auth.LoginResponse
	6,  // 15: auth.Auth.Verify:output_type -> auth.VerifyResponse
	19, // 16: auth.Auth.VerifyEmail:output_type -> google.protobuf.Empty
	10, // 17: auth.Auth.GetCurrentSession:output_type -> auth.GetCurrentSessionResponse
	12, // 18: auth.Auth.GetAllUserSessions:output_type -> auth.GetAllUserSessionsResponse
	14, // 19: auth.Auth.OauthLogin:output_type -> auth.OauthLoginResponse
	16, // 20: auth.Auth.OauthCallback:output_type -> auth.OauthCallbackResponse
	18, // 21: auth.Auth.EnableTotp:output_type -> auth.EnableTotpResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_proto_init() }
func file_proto_auth_auth_proto_init() {
	if File_proto_auth_auth_proto != nil {
		return
	}
	file_proto_auth_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_auth_auth_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_proto_depIdxs,
		EnumInfos:         file_proto_auth_auth_proto_enumTypes,
		MessageInfos:      file_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_proto = out.File
	file_proto_auth_auth_proto_goTypes = nil
	file_proto_auth_auth_proto_depIdxs = nil
}
